name: pp_gui
description: Эталонное GUI-приложение для протокола PP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_selector: ^1.0.3
  window_manager: ^0.5.1
  tray_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_512.png
    - assets/app_icon.ico
